### ISSUE TITLE
Initializing and unsealing

### ISSUE THREAD

**Issue by vijaybandari** [johnbellone/vault-cookbook#69]
Just want to discuss how you guys handle initializing and unsealing business.

We are trying to do this through chef, because it's not practical to unseal in the middle of night when something goes wrong & the service gets restarted and when it happens on 2 nodes in a 3 node cluster. The whole idea of cheffing is to automate setup and recovery mechanism. So wondering what's the process everybody following in this regard.

**Comment by legal90** [comment]
I've also thought about this but seems like it could not be automated by the convenient way. 

From docs:
```
Note: Unsealing makes the process of automating a Vault install difficult. Automated tools can easily install, configure, and start Vault, but unsealing it is a very manual process. We have plans in the future to make it easier. For the time being, the best method is to manually unseal multiple Vault servers in HA mode. Use a tool such as Consul to make sure you only query Vault servers that are unsealed.
```
https://www.vaultproject.io/docs/concepts/seal.html

P.s.
Even if it would be implemented, the automated init & unseal sound good only for testing purposes. It shouldn't be used in production because of security reasons. The initial idea of splitting the master key into shards was designed to avoid a single point of "failure". The shard of unseal keys also allows to generate a new root token, so it's even highly recommended to avoid the situation when the single operator knows all the unseal keys. 
So at this point, it would be really insecure if Chef will be able to unseal the Vault without operators.

**Comment by Ginja** [comment]
I agree with @legal90. It's best not to automate this. Also, if you're being required to unseal often because of Vault restarting/crashing, I'd say that's your issue.

**Comment by vijaybandari** [comment]
@legal90 & @Ginja Thank you for your responses. I too agree with you guys, but for our own reasons we have to automate it :). Fortunately it turned out to be simple cli command with keys being kept in chef-vault (initialise manually and put the keys in chef-vault).
